# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_form.ui',
# licensing of 'main_window_form.ui' applies.
#
# Created: Thu Nov 28 16:58:13 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 778)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.document = QtWidgets.QLabel(self.layoutWidget)
        self.document.setObjectName("document")
        self.verticalLayout_2.addWidget(self.document)
        self.text_content = QtWidgets.QTextBrowser(self.layoutWidget)
        self.text_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.text_content.setObjectName("text_content")
        self.verticalLayout_2.addWidget(self.text_content)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.aspects_in_document = QtWidgets.QLabel(self.layoutWidget1)
        self.aspects_in_document.setObjectName("aspects_in_document")
        self.verticalLayout.addWidget(self.aspects_in_document)
        self.aspects_list = QtWidgets.QListWidget(self.layoutWidget1)
        self.aspects_list.setTextElideMode(QtCore.Qt.ElideNone)
        self.aspects_list.setWordWrap(True)
        self.aspects_list.setObjectName("aspects_list")
        self.verticalLayout.addWidget(self.aspects_list)
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.feature_list_label = QtWidgets.QLabel(self.layoutWidget2)
        self.feature_list_label.setObjectName("feature_list_label")
        self.verticalLayout_5.addWidget(self.feature_list_label)
        self.feature_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.feature_list.setObjectName("feature_list")
        self.verticalLayout_5.addWidget(self.feature_list)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stop_list = QtWidgets.QLabel(self.layoutWidget3)
        self.stop_list.setObjectName("stop_list")
        self.verticalLayout_3.addWidget(self.stop_list)
        self.statistics = QtWidgets.QListView(self.layoutWidget3)
        self.statistics.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.statistics.setToolTip("")
        self.statistics.setStatusTip("")
        self.statistics.setObjectName("statistics")
        self.verticalLayout_3.addWidget(self.statistics)
        self.statistic_btn = QtWidgets.QPushButton(self.splitter_3)
        self.statistic_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.statistic_btn.setObjectName("statistic_btn")
        self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.progress_bar_layout = QtWidgets.QHBoxLayout()
        self.progress_bar_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.progress_bar_layout.setObjectName("progress_bar_layout")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.progress_bar_layout.addWidget(self.progress_bar)
        self.progress_label = QtWidgets.QLabel(self.centralwidget)
        self.progress_label.setObjectName("progress_label")
        self.progress_bar_layout.addWidget(self.progress_label)
        self.gridLayout.addLayout(self.progress_bar_layout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 943, 39))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.open_document = QtWidgets.QAction(MainWindow)
        self.open_document.setObjectName("open_document")
        self.import_text = QtWidgets.QAction(MainWindow)
        self.import_text.setObjectName("import_text")
        self.save_document = QtWidgets.QAction(MainWindow)
        self.save_document.setObjectName("save_document")
        self.menuFile.addAction(self.open_document)
        self.menuFile.addAction(self.save_document)
        self.menu.addAction(self.import_text)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.document.setText(QtWidgets.QApplication.translate("MainWindow", "Документ", None, -1))
        self.aspects_in_document.setText(QtWidgets.QApplication.translate("MainWindow", "Аспекты в документе", None, -1))
        self.feature_list_label.setText(QtWidgets.QApplication.translate("MainWindow", "Аспекты", None, -1))
        self.stop_list.setText(QtWidgets.QApplication.translate("MainWindow", "Список слов исключённых из аспектов", None, -1))
        self.statistic_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Статистика", None, -1))
        self.progress_bar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "ыва", None, -1))
        self.progress_bar.setFormat(QtWidgets.QApplication.translate("MainWindow", "%p%", None, -1))
        self.progress_label.setText(QtWidgets.QApplication.translate("MainWindow", "Поиск аспектов", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "Файл", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Текст", None, -1))
        self.open_document.setText(QtWidgets.QApplication.translate("MainWindow", "Открыть документ", None, -1))
        self.import_text.setText(QtWidgets.QApplication.translate("MainWindow", "Импортировать текст", None, -1))
        self.save_document.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить документ", None, -1))

